<table width="720" align="center" bgcolor="#EEEEEE" cellpadding="0" cellspacing="0" style="border:1px solid #DEDEDE;">
    <tr>
        <td width="15"></td>
        <td height="10"></td>
        <td width="15"></td>
    </tr>
    <tr>
        <td width="15"></td>
        <td height="20" style="font-family: Trebuchet, Arial, sans-serif;font-size: 14px;font-weight: bold;">
            %TITLE%
        </td>
        <td width="15"></td>
    </tr>
    <tr>

        <td width="15" height="2" style="line-height:0;">&nbsp;</td>
        <td height="2" width="690" style="line-height:0;border-bottom:2px solid #098364;width:690px;">&nbsp;</td>
        <td height="2" width="15" style="line-height:5px;">&nbsp;</td>

    </tr>
    <tr>
        <td width="15"></td>
        <td style="font-family: Trebuchet, Arial, sans-serif;font-size: 14px;font-weight: normal;">
            <br/>%MESSAGE%<br/><br/>
            <table cellpadding="0" cellspacing="0" width="640" align="center">
                <tr>
                    <td style="background-color:#FEFEFE;border:1px solid #CCC;">
                        <table>
                            <tr>
                                <td width="10"></td>
                                <td style="font-family: Courier New, Courier;font-size:11px;font-weight: normal;">
                                    <pre style="font-size:11px;">
                                    %REQUEST%

                                    API: %API_URL%
                                    </pre>

                                </td>
                                <td width="10"></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="background-color:#EEEEEE;height:10px;"></td>
                </tr>
            </table>
        </td>
        <td width="15"></td>
    </tr>
    <tr>

        <td width="15" height="2" style="line-height:0;">&nbsp;</td>
        <td height="2" width="690" style="line-height:0;border-bottom:2px solid #098364;width:690px;">&nbsp;</td>
        <td height="2" width="15" style="line-height:5px;">&nbsp;</td>

    </tr>
    <tr>

        <td width="15" height="2" style="line-height:0;">&nbsp;</td>
        <td height="2" width="690" style="line-height:0;width:690px;">&nbsp;</td>
        <td height="2" width="15" style="line-height:15px;">&nbsp;</td>

    </tr>
</table>
<table width="690" align="center" style="font-size:10px; font-family: Trebuchet MS, Trebuchet, Arial">
    <tr>
        <td>
            %FOOTER%
        </td>
    </tr>
</table>