<div id="block-abandoned-carts">
    <div style="min-height:85px;margin-bottom:12px;">
        <div class="inside">
            <?php echo $this->__('Abandoned carts interface allows you to get list of abandoned carts which you can import to SARE and use in your email markting actions.') ?><br/>
            <?php echo $this->__('Read more <a href=\"#\">here</a>.') ?>
            &nbsp;<b><?php echo $this->__('Interface URL:') ?></b><br/>
            <div class="url">
                <a style="color: black;text-decoration: none;" href="<?php echo $this->getInterfaceUrl();?>"><?php echo $this->getInterfaceUrl();?></a>
            </div>
        </div>
    </div>
</div>

