
<div id="block-targeting">
    <div class="inside">
        <div>
            <?php echo $this->__("Advanced targeting options allow you to update your recipents list with always up to date customers' data, for instance: last order grand total value, average basket value, number of logins.") ?><br/>
            <?php echo $this->__('You can later use this data to segment and filter recipents groups. <a href=\"#\">Read more here</a>.') ?><br/>
            <button id="sare-toggler" class="scalable add" onclick="$('sare-labels').toggle();return false;"><span><span><?php echo $this->__('Needed properties...') ?></span></span></button>
        </div>
    </div>


    <?php $labels = $this->getList();?>

    <div class="labels" id="sare-labels">
        <div class="smaller-text">
            <?php echo $this->__('These are required features you need add in your database structure.');?><br/>
            <?php echo $this->__('You must create them before you start using integration. Otherwise - extended customer data will not be saved at SARE side.');?>
        </div>

        <?php foreach($labels as $key=>$label){?>
            <div class="row">
                <div class="sare-key"><?php echo $key;?></div>
                <div class="sare-label"><?php echo $label['label'];?></div>
            </div>
        <?php } ?>
    </div>

</div>

<script type="text/javascript">
    document.observe("dom:loaded", function() {
        // initially hide all containers for tab content
       $('sare-labels').toggle();
    });
</script>


